scrape_configs:
  - job_name: 'tracky-consumer'
    scheme: https
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ '3.36.77.62:8083' ]
    tls_config:
      insecure_skip_verify: true
