scrape_configs:
  - job_name: 'connectiontest'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:9090']    # 애플리케이션 호스트:포트
    scrape_interval: 15s                # 15초마다 스크래핑