version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tracky
      MYSQL_DATABASE: tracky
      MYSQL_USER: root
      MYSQL_PASSWORD: tracky
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
