spring:
  main:
    log-startup-info: true
  config:
    import: classpath:application-common.yml
  application:
    name: emulator
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8081

url:
  #  hub-service: "http://localhost:8082/hub/car"  # 로컬 환경 URL
  hub-service: "http://hub-service.hub1:8082/hub/car"  # 개발 환경 URL
