spring:
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-rabbitmq.yml
  application:
    name: tracky-consumer
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20000
        order_inserts: true
        order_updates: true

rabbitmq:
  batch:
    # 배치 리스너 관련 설정
    default-requeue-rejected: false
    enabled: true       # 배치 리스너 활성화
    size: 250            # 배치 크기
    timeout: 2000      # 타임아웃(ms) - 짧게 설정하여 메트릭 수집 빈도 향상
    consumer-batch-enabled: true  # 내부 배치 처리 기능 활성화

server:
  port: 8083

discord:
  enable: ${DISCORD_WEBHOOK_ENABLE:false}
  webhook-url: ${DISCORD_WEBHOOK_WEB_URL}
