version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: tracky-web-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/opt/homebrew/var/mysql/

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: tracky-rabbitmq
  #   restart: always
  #   ports:
  #     - "5672:5672"    # RabbitMQ default port
  #     - "15672:15672"  # Management UI port
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
  #   # volumes:
  #   #   - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mysql_data:
  # gradle-cache:
  # rabbitmq_data: