version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-tracky-web
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tracky
      MYSQL_DATABASE: tracky-web
      MYSQL_USER: tracky
      MYSQL_PASSWORD: tracky
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
