name: Notify Discord on PR Opened

on:
  pull_request:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send PR info to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d @- ${{ secrets.DISCORD_WEBHOOK }} <<EOF
{
  "username": "🚀 GitHub PR Bot",
  "embeds": [
    {
      "title": "🔔 새 Pull Request",
      "description": "**[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})**\\n\\n${{ github.event.pull_request.body || "설명 없음" }}\\n\\n👤 작성자: @${{ github.event.pull_request.user.login }}",
      "color": 5814783
    }
  ]
}
EOF
