spring:
  config:
    import:
      - classpath:application-common.yml
      - classpath:application-rabbitmq.yml
  application:
    name: tracky-hub

rabbitmq:
  exchange:
    car-info: car-info-exchange
    cycle-info: cycle-info-exchange
    dlx: dlx-exchange
  routing:
    on-key: onKey
    off-key: offKey
    dead-letter-key: deadLetterKey
server:
  port: 8082
